stages:
  ingestions:
    cmd: uv run python -m services.data.ingestions.main
    deps:
      - data/raw/time_series-2020-10-06.csv
      - services/data/ingestions
      - sql/staging
      - core/
    outs:
      - data/database.db

  preprocess:
    cmd: uv run python -m services.data.preprocessing.main
    deps:
      - data/database.db
      - services/data/preprocessing
      - sql/features
      - core/
    outs:
      - data/database.db
  
  marts:
    cmd: uv run python -m services.data.marts.main
    deps:
      - data/database.db
      - services/data/marts
      - sql/marts
      - core/
    outs:
      - data/database.db
  
  api:
    cmd: uv run python -m services.api.main
    deps:
      - data/database.db
      - services/api/
      - sql/marts
      - core/
    outs:
      - data/database.db
  
    