stages:
  ingestion:
    cmd: >
      docker run --rm
      -v $(pwd)/services/data/ingestion:/app/services/data/ingestion
      -v $(pwd)/data:/app/data load-forecast-ingestion
    deps:
      - data/raw/time_series-2020-10-06.csv
      - services/data/ingestion
      - sql/staging
      - configs/
      - core/
    outs:
      - data/raw/database.duckdb

  preprocessing:
    cmd: >
      docker run --rm
      -v $(pwd)/services/data/preprocessing:/app/services/data/preprocessing
      -v $(pwd)/data:/app/data load-forecast-preprocessing
    deps:
      - data/raw/database.duckdb
      - services/data/preprocessing
      - sql/features/
      - configs/
      - core/
    outs:
      - data/processed/

  marts:
    cmd: >
      docker run --rm
      -v $(pwd)/services/data/marts:/app/services/data/marts
      -v $(pwd)/data:/app/data load-forecast-marts
    deps:
      - data/processed/processed.parquet
      - services/data/marts
      - sql/marts/
      - configs/
      - core/
    outs:
      - data/marts/
