# configs/config.yaml

paths:
  raw_data: "data/raw/time_series-2020-10-06.csv"
  processed_data: "data/processed/processed.csv"
  database: "data/database.db"



# Parameters for SQL handeling
sql:
  transform: "transform.sql"
  chunk_size: 50000  # Rolls back to 5000 if not set for pandas
  table_name: "german_load_clean"  # Rolls back to >>german_load_clean<< if not set