# configs/config.yaml

paths:
  raw_file: "data/raw/time_series-2020-10-06.csv"
  processed_data: "data/processed/processed.csv"
  database: "data/database.db"


# Parameters for SQL handling
sql:
  root: sql
  chunk_size: 50000
  tables:
    raw_source_table: "raw_source_data"
    staging: "stg_german_load"
    features: "fct_german_load"
    marts: "german_load_api"
  entrypoints:
    staging:
      stg_german_load: "staging/stg_german_load.sql"
    features:
      fct_german_load: "features/fct_german_load.sql"
    marts:
      german_load_api: "marts/german_load_api.sql"
    quality:
      target_overview: "quality/target_overview.sql"


# logging settings for pipeline services
logging:
  level: "INFO"
  to_console: true
  service_logs:
    ingestion: "ingest.log"
    preprocessing: "preprocess.log"


# API settings
api:
  templates: "services/api/templates"
