# configs/config.yaml

paths:
  raw_data: "data/raw/time_series-2020-10-06.csv"
  processed_data: "data/processed/processed.csv"
  database: "data/database.db"



# Parameters for SQL handeling
sql:
  target_table: "german_load_clean"
  chunk_size: 50000
  transform: "transform.sql"
  quality_check: "quality_check.sql"


# logging settings for pipeline services
logging:
  level: "INFO"
  to_console: true
  ingestion_log: "ingest.log"
  preprocessing_log: "preprocess.log"


# API settings
api:
  templates: "services/api/templates"
